# Generated by Django 4.2.4 on 2024-08-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jana',
            name='address',
            field=models.TextField(default='chennai'),
        ),
        migrations.AddField(
            model_name='jana',
            name='course',
            field=models.CharField(choices=[('python', 'PYTHON'), ('java', 'JAVA'), ('c', 'C'), ('web design', 'WEB DESIGN')], default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='jana',
            name='mobile',
            field=models.BigIntegerField(default=0),
        ),
    ]
