# Generated by Django 4.2.4 on 2024-08-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_jana_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='jana',
            name='image',
            field=models.ImageField(default='NULL', upload_to=''),
        ),
        migrations.AlterField(
            model_name='jana',
            name='mobile',
            field=models.BigIntegerField(default=0, help_text='mobile no should be 10 digits'),
        ),
        migrations.AlterField(
            model_name='jana',
            name='name',
            field=models.CharField(max_length=10, verbose_name='ENTER NAME'),
        ),
    ]
