# Generated by Django 4.2.4 on 2024-09-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_jana_image_alter_jana_mobile_alter_jana_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='ENTER NAME')),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(help_text='mobile no should be 10 digits')),
                ('address', models.TextField(default='chennai')),
                ('course', models.CharField(choices=[('python', 'PYTHON'), ('java', 'JAVA'), ('c', 'C'), ('web design', 'WEB DESIGN'), ('django', 'DJANGO'), ('c++', 'CPP'), ('advancejava', 'ADVANCE JAVA')], default='python', max_length=20)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='NULL', upload_to='')),
                ('fees', models.BooleanField(default=False)),
            ],
        ),
    ]
